### ISSUE TITLE
`max_idle_pool_size` usage causes "disappearing" fibers

### ISSUE THREAD

**Issue by emil-rb** [crystal-lang/crystal-db#182]
Under load, when actively using the db pool some fibers "disappear". I assume they are blocked somewhere. In the repo below we provide two reproductions - one using a simple web interface and load tested using ab (Apache Benchmark) and one using a simple script that just spawns a bunch of fibers and tries to use the pool.

This only happens when fiddling with the `max_idle_pool_size` param. In this example we want a fixed pool, hence `initial_pool_size=5&max_pool_size=5&max_idle_pool_size=5`. See the repo for details on how to reproduce this.

This has already been [discussed in the forum](https://forum.crystal-lang.org/t/concurrency-issues-with-an-api-server/5482) a while ago.

[Github repo for reproduction](https://github.com/emil-rb/crystal-db-pool-issue)

**Comment by bcardiff** [comment]
Master includes #178 which wasn't released yet. That seems  related to this issue. You can override crystal-db to be master and check today if that fixes or wait for a release of 0.12 and release of crystal-pg for that.

**Comment by bcardiff** [comment]
I appreciate the repro repo 🙇

**Comment by emil-rb** [comment]
I've updated the repro repo to use `crystal-db` from master, but the problem still persists and can be reproduced by both methods (web and in-memory). On both a few requests never come back (<5 usually, sometimes 0).

**Comment by mitio** [comment]
Hey @bcardiff did you have a chance to look at this?

**Comment by bcardiff** [comment]
Between the information here and in the forum I think that one thing that can be happening is that the fibers are stuck in either waiting a response from the DB or waiting something in the http socket. In either way I think the best approach would be to include a TTL on the connection itself. That would allow the pool to drop old connections that are stuck for whatever reason and allow the pool to create new connections when needed.

Another possibility is that indeed there exist some bug in the `@idle` handling. I keep staring at the code in case there is an eureka moment 👀 

The forum post also mention another issue that I think is fixed by #184 .

**Comment by emil-rb** [comment]
In the repro repo above there's an example without http and it still reproduces. Using a `max_idle_pool_size` of 0 doesn't trigger it, so it definitelly looks like a race condition in the pool. I also spent some time looking at the code and didn't see the bug outright. But the code makes some strange choices of releasing the lock and re-squiring it a line or two below, which makes the code hard to reason - what if another fiber grabs the lock in the meantime.

**Comment by bcardiff** [comment]
I think I found something :-) 

Fibers seems to be stuck

```
      if idle_pushed && are_waiting_for_resource?
        # HERE
        @availability_channel.send nil
      end
```

I think `are_waiting_for_resource?` could change value between the check and the channel send. 
Maybe replacing that with a non-blocking select would be better.

@emil-rb could you monkey-patch your code with the following to see if it works better for you.

```crystal
module DB
  class Pool(T)
    def release(resource : T) : Nil
      idle_pushed = false

      sync do
        if resource.responds_to?(:closed?) && resource.closed?
          @total.delete(resource)
        elsif can_increase_idle_pool
          @idle << resource
          if resource.responds_to?(:after_release)
            resource.after_release
          end
          idle_pushed = true
        else
          resource.close
          @total.delete(resource)
        end
      end

      if idle_pushed
        select
        when @availability_channel.send(nil)
        else
        end
      end
    end
  end
end
```

---

What dirty thing I did to narrow this?

1. I named the producer fibers `spawn(name: "prod #{index}") do`
2. I create a forever loop with a 5 sec sleep to print where where the remaining producers fibers that are still running

```crystal
    spawn do
      loop do
        fs = [] of Fiber
        Fiber.unsafe_each do |fiber|
          fs << fiber if fiber.name.try(&.starts_with?("prod"))
        end

        # print stuff of fs (important to not do IO while we are building the summary)

        sleep 5
      end
    end
```

3. I wanted to know _where_ there fiber was stuck, so I extended Fiber with some context.

```crystal
class Fiber
  property section : String = "()"

  def self.trace(section : String)
    Fiber.current.section = section
  end
end
```

4. Like if there were no tomorrow add `Fiber.trace` all around like puts debugging

```crystal
      if idle_pushed && are_waiting_for_resource?
        Fiber.trace "release5"
        @availability_channel.send nil
        Fiber.trace "release6"
      end
```

5. profit

**Comment by emil-rb** [comment]
Great! Initial tests with the repro repo don't reproduce the issue.
